### ISSUE TITLE
vagrant up --provider virtualbox

### ISSUE THREAD

**Issue by cbazaes-isw** [malarcon-79/inf3550-composer#1]
@malarcon-79 Al ejecutar el comando `vagrant up --provider virtualbox` la consola me arroja el siguiente mensaje:
![image](https://user-images.githubusercontent.com/23032594/69721053-c4511680-10f2-11ea-9683-5e9b7a9672a9.png)

Hace unos minutos actualicé el script con el último commit.

**Comment by cbazaes-isw** [comment]
capa 8

**Comment by malarcon-79** [comment]
Good
